### ISSUE TITLE
Cannot read property 'func' of undefined

### ISSUE THREAD

**Issue by TopGuo** [chong2230/geekTime#1]
你好，在你项目里你使用了react-native-viewpager，这个组建，我在调Android的时候，报了Cannot read property 'func' of undefined这个错误，github给出的解释是：[](https://github.com/race604/react-native-viewpager/issues/173)

这个组建已经过期了，很多api已经更新了，如果想继续用，那就等作者更新最新版本，rn项目中PropType的问题。等不了的朋友可以换 react native swiper

建议更换此组建，以保证项目..

**Comment by chong2230** [comment]
我再Readme上说明了，“由于RN版本更新，需将tools目录下ViewPager.js和DefaultViewPageIndicator.js覆盖node_modules/react-native-viewpager下对应文件”，对PropType做了修改，react-native-viewpager最近也没更新了
