### ISSUE TITLE
Cannot add a child that doesn't have a YogaNode to a parent without a measure function

### ISSUE THREAD

**Issue by TopGuo** [chong2230/geekTime#2]
再来一个issues，Android上出现red box，提示Cannot add a child that doesn't have a YogaNode to a parent without a measure function
github解决：https://github.com/facebook/react-native/issues/18773

**Comment by chong2230** [comment]
语法有误，多了个 { 字符，已修复

**Comment by TopGuo** [comment]
你又复活了？
