### ISSUE TITLE
:react-native-video

### ISSUE THREAD

**Issue by TopGuo** [chong2230/geekTime#4]
作者跟新有点快：是不是Android的依然没有调试？
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-video'.
      > Failed to find Platform SDK with path: platforms;android-27
![image](https://user-images.githubusercontent.com/30146744/44663732-ecf7e580-aa43-11e8-918f-4bddbee1dbca.png)

slove:
https://github.com/react-native-community/react-native-video
![image](https://user-images.githubusercontent.com/30146744/44663995-9c34bc80-aa44-11e8-85dc-0b2067fdba83.png)

再补充一点，这个组建发生什么什么变化，确实需要配置一些东西
https://github.com/react-native-community/react-native-video/issues/1079
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven { url "https://maven.google.com" }
    }
    project.ext {
        compileSdkVersion = 23
        buildToolsVersion = "23.0.1"
        minSdkVersion = 16
        targetSdkVersion = 22
    }
}
![image](https://user-images.githubusercontent.com/30146744/44668474-1454af80-aa50-11e8-9499-d6b1e581771d.png)

**Comment by chong2230** [comment]
After add properties above, it's also wrong like this.

JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-video'.
      > Could not resolve all dependencies for configuration ':react-native-video:_debugCompile'.
         > Could not determine artifacts for org.webkit:android-jsc:r174650
            > Could not get resource 'https://jcenter.bintray.com/org/webkit/android-jsc/r174650/android-jsc-r174650.aar'.
               > Could not HEAD 'https://jcenter.bintray.com/org/webkit/android-jsc/r174650/android-jsc-r174650.aar'.
                  > Remote host closed connection during handshake

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by TopGuo** [comment]
这个bug 你项目修复了？

**Comment by chong2230** [comment]
app/build.gradle修改
android {
    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
    compileSdkVersion 23
    // buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "com.geekTime"
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    implementation project(':react-native-code-push')
    implementation project(':react-native-fileupload')
    implementation project(':react-native-video')
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-sound')
    implementation project(':react-native-picker')
    implementation project(':react-native-orientation')
    implementation project(':react-native-image-picker')
    implementation project(':react-native-i18n')
    implementation project(':react-native-http-cache')
    implementation project(':react-native-video')
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-picker')
    implementation project(':react-native-sound')
    implementation project(':react-native-orientation')
    implementation project(':react-native-image-picker')
    implementation project(':react-native-i18n')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:23.0.1"
    implementation "com.facebook.react:react-native:+"  // From node_modules
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

在根目录下memo.txt有对应说明
配置里面有些api过时了 https://blog.csdn.net/Song_74110/article/details/80387307
需要改成如下： 
compile 改成 implementation 
androidTestCompile 改成 androidTestImplementation 
testCompile 改成 testImplementation
provided 改成 compileOnly

 implementation project(':react-native-orientation')
这个按需添加，我这里列的比较多

7. android studio 3.1 升级gradle4.4时所踩到的坑
https://blog.csdn.net/Public_x/article/details/80224838
项目使用的Gradle是3.3版本的，而Android studio3.1 所使用的Gradle版本是4.4
gradle/wrapper/gradle-wrapper.properties
修改distributionUrl
distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip

经过相关修改，可以解决大部分android运行错误
